name: wsl-image-builder
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  run-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run builder
        run: nix run .#nixosConfigurations.wsl-kun.config.system.build.tarballBuilder
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: wsl-kun
          path: nixos-wsl.tar.gz
